branches:
  only:
  - master
language: python
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
python:
- "2.7_with_system_site_packages"
- '2.6'
before_install:
- sudo add-apt-repository ppa:cython-dev/master-ppa -y
- sudo apt-get install cython
install:
- pip install requirements
- pip install python-coveralls
- cython affinegap/*.pyx
- python setup.py develop
script:
- coverage run -m nose
after_success: coveralls
