branches:
  only:
  - master
language: python
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
sudo: false
python:
- "2.7"
- '3.4'
install:
- pip install -r requirements.txt
- cython affinegap/*.pyx
- python setup.py develop
script:
- nosetests
